---
name: instagram_clone
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  cloud_firestore: ^4.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  firebase_storage: ^11.0.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  image_picker: ^0.8.6
  provider: ^6.0.4
  uuid: ^3.0.6
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.6.2
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/logo-text.png
